name: Build and Deploy React App

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: CI=false npm run build

    - name: Find main JS file
      id: find_js
      run: |
        main_js_file=$(basename $(ls build/static/js/main.*.js))
        echo "main_js_file=$main_js_file" >> $GITHUB_ENV

    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local_path: ./build/
        remote_path: /var/www/radioplayer_build/

    - name: Create Symlink via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        script: |
          ln -sf /var/www/radioplayer_build/static/js/${{ env.main_js_file }} /var/www/static/radioPlayer.js
          echo "Symlink created for ${{ env.main_js_file }}"
